/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOSEFU
 */
public class Presupuestos extends javax.swing.JFrame {

    /**
     * Creates new form Presupuestos
     */
    public Presupuestos() {
        initComponents();
        cargarDatosPresupuestos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPresupuestos = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtidPresupuesto1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtidUsuario1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtmontoLimite1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fechaInicio1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfechaFin1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Presupuestos");

        tablaPresupuestos.setBackground(new java.awt.Color(255, 255, 255));
        tablaPresupuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Presupuesto", "ID Usuario", "Monto Limite", "Fecha Inicio", "Fecha Fin", "Nombre del Presupuesto ", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tablaPresupuestos);
        if (tablaPresupuestos.getColumnModel().getColumnCount() > 0) {
            tablaPresupuestos.getColumnModel().getColumn(3).setResizable(false);
        }

        btnVolver.setBackground(new java.awt.Color(0, 102, 102));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 102, 102));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Presupuesto");

        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        jLabel4.setText("ID Usuario");

        txtidPresupuesto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidPresupuesto1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Monto Limite");

        txtidUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidUsuario1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha Inicio");

        txtmontoLimite1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmontoLimite1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Fecha Fin");

        fechaInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaInicio1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre");

        txtfechaFin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaFin1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Tipo");

        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(0, 102, 102));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar Presupuesto");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(461, 461, 461))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnActualizar)
                            .addComponent(btnVolver, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(txtidPresupuesto1)
                            .addComponent(txtTipo)
                            .addComponent(txtmontoLimite1)
                            .addComponent(fechaInicio1)
                            .addComponent(txtfechaFin1)
                            .addComponent(txtNombre1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnActualizar)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidPresupuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtidUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtmontoLimite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fechaInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtfechaFin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(46, 46, 46)
                .addComponent(btnVolver)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

        this.dispose();
        Menu menu = new Menu();
        menu.setVisible(true);

    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        cargarDatosPresupuestos();


    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void txtidPresupuesto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidPresupuesto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidPresupuesto1ActionPerformed

    private void txtidUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidUsuario1ActionPerformed

    private void txtmontoLimite1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmontoLimite1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmontoLimite1ActionPerformed

    private void fechaInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaInicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaInicio1ActionPerformed

    private void txtfechaFin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaFin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaFin1ActionPerformed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        try {
            int idPresupuesto = Integer.parseInt(txtidPresupuesto1.getText());
            int idUsuario = Integer.parseInt(txtidUsuario1.getText());
            double montoLimite = Double.parseDouble(txtmontoLimite1.getText());
            String fechaInicio = fechaInicio1.getText();  
            String fechaFin = txtfechaFin1.getText();   
            String nombrePresupuesto = txtNombre1.getText();
            String tipo = txtTipo.getText();

            // Validar el formato de las fechas
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            sdf.setLenient(false); // Validación estricta
            java.util.Date utilFechaInicio = sdf.parse(fechaInicio);
            java.util.Date utilFechaFin = sdf.parse(fechaFin);

            // Convertir java.util.Date a java.sql.Date
            java.sql.Date sqlFechaInicio = new java.sql.Date(utilFechaInicio.getTime());
            java.sql.Date sqlFechaFin = new java.sql.Date(utilFechaFin.getTime());

            // Conexión a la base de datos
            Connection conn = proyecto_bd.OracleConnection.conectar();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos.");
                return;
            }

            String sql = "INSERT INTO presupuestos (id_presupuesto, id_usuario, monto_limite, fecha_inicio, fecha_fin, nombre_presupuesto, tipo) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, idPresupuesto);
            pst.setInt(2, idUsuario);
            pst.setDouble(3, montoLimite);
            pst.setDate(4, sqlFechaInicio);  // Fechas convertidas
            pst.setDate(5, sqlFechaFin);
            pst.setString(6, nombrePresupuesto);
            pst.setString(7, tipo);

            int filasAfectadas = pst.executeUpdate();
            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(this, "Presupuesto agregado exitosamente.");
                cargarDatosPresupuestos();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo agregar el presupuesto.");
            }

            pst.close();
            conn.close();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos para ID y Monto Límite.");
        } catch (java.text.ParseException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese fechas válidas en el formato dd-MM-yyyy.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al agregar el presupuesto: " + e.getMessage());
        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void limpiarCampos() {
        txtidPresupuesto1.setText("");
        txtidUsuario1.setText("");
        txtmontoLimite1.setText("");
        fechaInicio1.setText("");
        txtfechaFin1.setText("");
        txtNombre1.setText("");
        txtTipo.setText("");
    }

    private void cargarDatosPresupuestos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Presupuesto");
        modelo.addColumn("ID Usuario");
        modelo.addColumn("Monto Límite");
        modelo.addColumn("Fecha Inicio");
        modelo.addColumn("Fecha Fin");
        modelo.addColumn("Nombre del Presupuesto");
        modelo.addColumn("Tipo");

        tablaPresupuestos.setModel(modelo);

        try {
            Connection conn = (Connection) proyecto_bd.OracleConnection.conectar();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos.");
                return;
            }

            String sql = "SELECT id_presupuesto, id_usuario, monto_limite, fecha_inicio, fecha_fin, nombre_presupuesto, tipo FROM presupuestos";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[7];
                fila[0] = rs.getInt("id_presupuesto");
                fila[1] = rs.getInt("id_usuario");
                fila[2] = rs.getDouble("monto_limite");
                fila[3] = rs.getDate("fecha_inicio");
                fila[4] = rs.getDate("fecha_fin");
                fila[5] = rs.getString("nombre_presupuesto");
                fila[6] = rs.getString("tipo");

                modelo.addRow(fila);
            }

            rs.close();
            pst.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los presupuestos: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presupuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presupuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presupuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presupuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presupuestos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField fechaInicio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPresupuestos;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtfechaFin1;
    private javax.swing.JTextField txtidPresupuesto1;
    private javax.swing.JTextField txtidUsuario1;
    private javax.swing.JTextField txtmontoLimite1;
    // End of variables declaration//GEN-END:variables
}
